In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import math
import seaborn as sns
from scipy import stats
from statsmodels.stats.power import TTestIndPower
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
NBA_Stats = pd.read_csv(r'C:\Users\ASUS\Thinkful_Projects\Capstone_1\NBA_Stats.csv').drop(columns='Unnamed: 0').dropna(axis=0)

In [58]:
NBA_Drafts = pd.read_csv(r'C:\Users\ASUS\Thinkful_Projects\Capstone_1\NBA_Drafts.csv').drop(columns='Unnamed: 0').rename(columns={'SEASON': 'DRAFT_SEASON', 'TEAM_ID':'DRAFT_TEAM_ID', 'TEAM_ABBREVIATION': 'DRAFT_TEAM_ABBREVIATION'})

In [59]:
NBA_Stats

,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,MIN,...,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS,SEASON
0,201985,AJ Price,1.610613e+09,IND,24.0,50,22,28,0.440,15.9,...,351,198,240,161,274,224,27,5,"201985,1610612754",2010-11
1,201166,Aaron Brooks,1.610613e+09,PHX,26.0,59,26,33,0.441,21.8,...,205,131,132,377,179,154,27,5,"201166,1610612756",2010-11
2,201189,Aaron Gray,1.610613e+09,NOH,26.0,41,21,20,0.512,12.9,...,121,348,362,145,326,154,27,5,"201189,1610612740",2010-11
3,201151,Acie Law,1.610613e+09,GSW,26.0,51,20,31,0.392,14.2,...,357,265,321,368,335,224,27,5,"201151,1610612744",2010-11
4,1733,Al Harrington,1.610613e+09,DEN,31.0,73,45,28,0.616,22.8,...,55,199,137,97,176,181,27,5,"1733,1610612743",2010-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5422,1627812,Yogi Ferrell,1.610613e+09,CLE,27.0,2,0,2,0.000,20.3,...,161,92,183,461,161,157,19,5,"1627812,1610612739",2020-21
5423,1629139,Yuta Watanabe,1.610613e+09,TOR,26.0,18,11,7,0.611,12.4,...,356,370,378,168,333,157,19,5,"1629139,1610612761",2020-21
5424,203897,Zach LaVine,1.610613e+09,CHI,25.0,25,10,15,0.400,35.5,...,64,39,7,379,20,78,19,5,"203897,1610612741",2020-21
5425,1630192,Zeke Nnaji,1.610613e+09,DEN,20.0,12,9,3,0.750,4.0,...,444,447,419,397,449,157,19,5,"1630192,1610612743",2020-21
5426,1629627,Zion Williamson,1.610613e+09,NOP,20.0,25,11,14,0.440,32.7,...,60,11,18,211,33,31,19,5,"1629627,1610612740",2020-21

In [60]:
NBA_Stats.isnull().sum().sum()

0

In [57]:
NBA_Drafts

,PERSON_ID,PLAYER_NAME,DRAFT_SEASON,ROUND_NUMBER,ROUND_PICK,OVERALL_PICK,DRAFT_TYPE,DRAFT_TEAM_ID,TEAM_CITY,TEAM_NAME,DRAFT_TEAM_ABBREVIATION,ORGANIZATION,ORGANIZATION_TYPE,PLAYER_PROFILE_FLAG
0,202322,John Wall,2010,1,1,1,Draft,1610612764,Washington,Wizards,WAS,Kentucky,College/University,1
1,202323,Evan Turner,2010,1,2,2,Draft,1610612755,Philadelphia,76ers,PHI,Ohio State,College/University,1
2,202324,Derrick Favors,2010,1,3,3,Draft,1610612751,New Jersey,Nets,NJN,Georgia Tech,College/University,1
3,202325,Wesley Johnson,2010,1,4,4,Draft,1610612750,Minnesota,Timberwolves,MIN,Syracuse,College/University,1
4,202326,DeMarcus Cousins,2010,1,5,5,Draft,1610612758,Sacramento,Kings,SAC,Kentucky,College/University,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,1630203,Grant Riller,2020,2,26,56,Draft,1610612766,Charlotte,Hornets,CHA,College of Charleston,College/University,1
656,1629617,Reggie Perry,2020,2,27,57,Draft,1610612746,LA,Clippers,LAC,Mississippi State,College/University,1
657,1630194,Paul Reed,2020,2,28,58,Draft,1610612755,Philadelphia,76ers,PHI,DePaul,College/University,1
658,1630223,Jalen Harris,2020,2,29,59,Draft,1610612761,Toronto,Raptors,TOR,Nevada-Reno,College/University,1
659,1630241,Sam Merrill,2020,2,30,60,Draft,1610612740,New Orleans,Pelicans,NOP,Utah State,College/University,1

In [19]:
NBA_Drafts.isnull().sum()

PERSON_ID              0
PLAYER_NAME            0
DRAFT_SEASON           0
ROUND_NUMBER           0
ROUND_PICK             0
OVERALL_PICK           0
DRAFT_TYPE             0
TEAM_ID                0
TEAM_CITY              0
TEAM_NAME              0
TEAM_ABBREVIATION      0
ORGANIZATION           2
ORGANIZATION_TYPE      2
PLAYER_PROFILE_FLAG    0
dtype: int64

In [20]:
NBA_Drafts.loc[NBA_Drafts['ORGANIZATION'].isnull()]

,PERSON_ID,PLAYER_NAME,DRAFT_SEASON,ROUND_NUMBER,ROUND_PICK,OVERALL_PICK,DRAFT_TYPE,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,ORGANIZATION,ORGANIZATION_TYPE,PLAYER_PROFILE_FLAG
369,1627748,Thon Maker,2016,1,10,10,Draft,1610612749,Milwaukee,Bucks,MIL,NaN,NaN,1
515,1629011,Mitchell Robinson,2018,2,6,36,Draft,1610612752,New York,Knicks,NYK,NaN,NaN,1

In [21]:
#NBA_Drafts.fillna('Missing')

In [22]:
NBA_Drafts.ORGANIZATION_TYPE.value_counts()

College/University    535
Other Team/Club       118
High School             5
Name: ORGANIZATION_TYPE, dtype: int64

In [23]:
NBA_Drafts.ROUND_NUMBER.value_counts()

2    330
1    330
Name: ROUND_NUMBER, dtype: int64

In [25]:
NBA_Drafts.columns

Index(['PERSON_ID', 'PLAYER_NAME', 'DRAFT_SEASON', 'ROUND_NUMBER',
       'ROUND_PICK', 'OVERALL_PICK', 'DRAFT_TYPE', 'TEAM_ID', 'TEAM_CITY',
       'TEAM_NAME', 'TEAM_ABBREVIATION', 'ORGANIZATION', 'ORGANIZATION_TYPE',
       'PLAYER_PROFILE_FLAG'],
      dtype='object')

In [26]:
NBA_Stats.isnull().sum().sum()

0

In [27]:
NBA_df = NBA_Drafts.merge(NBA_Stats, how='outer', on='PLAYER_NAME')

In [28]:
NBA_df

,PERSON_ID,PLAYER_NAME,DRAFT_SEASON,ROUND_NUMBER,ROUND_PICK,OVERALL_PICK,DRAFT_TYPE,TEAM_ID_x,TEAM_CITY,TEAM_NAME,...,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS,SEASON
0,202322.0,John Wall,2010.0,1.0,1.0,1.0,Draft,1.610613e+09,Washington,Wizards,...,89.0,21.0,47.0,450.0,20.0,25.0,7.0,5.0,"202322,1610612764",2010-11
1,202322.0,John Wall,2010.0,1.0,1.0,1.0,Draft,1.610613e+09,Washington,Wizards,...,171.0,12.0,42.0,429.0,22.0,28.0,14.0,5.0,"202322,1610612764",2011-12
2,202322.0,John Wall,2010.0,1.0,1.0,1.0,Draft,1.610613e+09,Washington,Wizards,...,84.0,13.0,17.0,129.0,21.0,53.0,27.0,5.0,"202322,1610612764",2012-13
3,202322.0,John Wall,2010.0,1.0,1.0,1.0,Draft,1.610613e+09,Washington,Wizards,...,51.0,34.0,23.0,83.0,14.0,21.0,6.0,5.0,"202322,1610612764",2013-14
4,202322.0,John Wall,2010.0,1.0,1.0,1.0,Draft,1.610613e+09,Washington,Wizards,...,113.0,42.0,29.0,44.0,11.0,7.0,21.0,5.0,"202322,1610612764",2014-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5486,NaN,Nate Hinton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,457.0,408.0,439.0,413.0,460.0,157.0,19.0,5.0,"1630207,1610612742",2020-21
5487,NaN,Nathan Knight,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,403.0,338.0,378.0,260.0,397.0,157.0,19.0,5.0,"1630233,1610612737",2020-21
5488,NaN,Sean McDermott,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,444.0,408.0,401.0,426.0,429.0,157.0,19.0,5.0,"1630253,1610612763",2020-21
5489,NaN,Trent Forrest,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,409.0,408.0,462.0,426.0,444.0,157.0,19.0,5.0,"1630235,1610612762",2020-21
5490,NaN,Ty-Shon Alexander,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,444.0,461.0,470.0,374.0,472.0,157.0,19.0,5.0,"1630234,1610612756",2020-21

3066 players in the stats.nba.com data were not drafted into the league.

In [29]:
NBA_df.loc[NBA_df['DRAFT_SEASON'].isnull()]

,PERSON_ID,PLAYER_NAME,DRAFT_SEASON,ROUND_NUMBER,ROUND_PICK,OVERALL_PICK,DRAFT_TYPE,TEAM_ID_x,TEAM_CITY,TEAM_NAME,...,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS,SEASON
2425,NaN,AJ Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,351.0,198.0,240.0,161.0,274.0,224.0,27.0,5.0,"201985,1610612754",2010-11
2426,NaN,AJ Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,440.0,362.0,341.0,157.0,350.0,203.0,14.0,5.0,"201985,1610612754",2011-12
2427,NaN,AJ Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,339.0,242.0,205.0,287.0,216.0,173.0,27.0,5.0,"201985,1610612764",2012-13
2428,NaN,AJ Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,473.0,468.0,443.0,208.0,468.0,234.0,27.0,5.0,"201985,1610612750",2013-14
2429,NaN,AJ Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,470.0,261.0,321.0,384.0,371.0,252.0,21.0,5.0,"201985,1610612739",2014-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5486,NaN,Nate Hinton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,457.0,408.0,439.0,413.0,460.0,157.0,19.0,5.0,"1630207,1610612742",2020-21
5487,NaN,Nathan Knight,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,403.0,338.0,378.0,260.0,397.0,157.0,19.0,5.0,"1630233,1610612737",2020-21
5488,NaN,Sean McDermott,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,444.0,408.0,401.0,426.0,429.0,157.0,19.0,5.0,"1630253,1610612763",2020-21
5489,NaN,Trent Forrest,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,409.0,408.0,462.0,426.0,444.0,157.0,19.0,5.0,"1630235,1610612762",2020-21
5490,NaN,Ty-Shon Alexander,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,444.0,461.0,470.0,374.0,472.0,157.0,19.0,5.0,"1630234,1610612756",2020-21

# Creating Draft Only Tabular Dataset

In [32]:
Drafted_NBA = NBA_df.dropna(axis=0, subset=['DRAFT_SEASON'])
Drafted_NBA

,PERSON_ID,PLAYER_NAME,DRAFT_SEASON,ROUND_NUMBER,ROUND_PICK,OVERALL_PICK,DRAFT_TYPE,TEAM_ID_x,TEAM_CITY,TEAM_NAME,...,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS,SEASON
0,202322.0,John Wall,2010.0,1.0,1.0,1.0,Draft,1.610613e+09,Washington,Wizards,...,89.0,21.0,47.0,450.0,20.0,25.0,7.0,5.0,"202322,1610612764",2010-11
1,202322.0,John Wall,2010.0,1.0,1.0,1.0,Draft,1.610613e+09,Washington,Wizards,...,171.0,12.0,42.0,429.0,22.0,28.0,14.0,5.0,"202322,1610612764",2011-12
2,202322.0,John Wall,2010.0,1.0,1.0,1.0,Draft,1.610613e+09,Washington,Wizards,...,84.0,13.0,17.0,129.0,21.0,53.0,27.0,5.0,"202322,1610612764",2012-13
3,202322.0,John Wall,2010.0,1.0,1.0,1.0,Draft,1.610613e+09,Washington,Wizards,...,51.0,34.0,23.0,83.0,14.0,21.0,6.0,5.0,"202322,1610612764",2013-14
4,202322.0,John Wall,2010.0,1.0,1.0,1.0,Draft,1.610613e+09,Washington,Wizards,...,113.0,42.0,29.0,44.0,11.0,7.0,21.0,5.0,"202322,1610612764",2014-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2420,1630203.0,Grant Riller,2020.0,2.0,26.0,56.0,Draft,1.610613e+09,Charlotte,Hornets,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2421,1629617.0,Reggie Perry,2020.0,2.0,27.0,57.0,Draft,1.610613e+09,LA,Clippers,...,176.0,378.0,358.0,336.0,342.0,103.0,19.0,5.0,"1629617,1610612751",2020-21
2422,1630194.0,Paul Reed,2020.0,2.0,28.0,58.0,Draft,1.610613e+09,Philadelphia,76ers,...,397.0,461.0,357.0,62.0,358.0,157.0,19.0,5.0,"1630194,1610612755",2020-21
2423,1630223.0,Jalen Harris,2020.0,2.0,29.0,59.0,Draft,1.610613e+09,Toronto,Raptors,...,359.0,461.0,470.0,188.0,477.0,157.0,19.0,5.0,"1630223,1610612761",2020-21
2424,1630241.0,Sam Merrill,2020.0,2.0,30.0,60.0,Draft,1.610613e+09,New Orleans,Pelicans,...,444.0,437.0,433.0,198.0,416.0,157.0,19.0,5.0,"1630241,1610612749",2020-21

In [38]:
Drafted_NBA.value_counts('PERSON_ID')

PERSON_ID
202329.0     11
202330.0     11
202340.0     11
202335.0     11
202334.0     11
             ..
1627757.0     1
1627766.0     1
1627771.0     1
1627773.0     1
202160.0      1
Length: 660, dtype: int64

In [42]:
NBA_df.DRAFT_TYPE.value_counts()

Draft    2425
Name: DRAFT_TYPE, dtype: int64

In [43]:
NBA_df.columns

Index(['PERSON_ID', 'PLAYER_NAME', 'DRAFT_SEASON', 'ROUND_NUMBER',
       'ROUND_PICK', 'OVERALL_PICK', 'DRAFT_TYPE', 'TEAM_ID_x', 'TEAM_CITY',
       'TEAM_NAME', 'TEAM_ABBREVIATION_x', 'ORGANIZATION', 'ORGANIZATION_TYPE',
       'PLAYER_PROFILE_FLAG', 'PLAYER_ID', 'TEAM_ID_y', 'TEAM_ABBREVIATION_y',
       'AGE', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS',
       'NBA_FANTASY_PTS', 'DD2', 'TD3', 'GP_RANK', 'W_RANK', 'L_RANK',
       'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK', 'FGA_RANK', 'FG_PCT_RANK',
       'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK', 'FTA_RANK',
       'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK', 'REB_RANK', 'AST_RANK',
       'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK', 'PFD_RANK',
       'PTS_RANK', 'PLUS_MINUS_RANK', 'NBA_FANTASY_PTS_RANK', 'DD2_RANK',
       'TD3_RANK', 'CFID', 'CFPARAMS', 'SEASON'],
      dtype='object')

In [ ]:
['TEAM_ID_x', 'TEAM_ABBREVIATION_x', ]

In [45]:
Drafted_NBA.loc[Drafted_NBA['PLAYER_NAME'] == 'Patty Mills']

Empty DataFrame
Columns: [PERSON_ID, PLAYER_NAME, DRAFT_SEASON, ROUND_NUMBER, ROUND_PICK, OVERALL_PICK, DRAFT_TYPE, TEAM_ID_x, TEAM_CITY, TEAM_NAME, TEAM_ABBREVIATION_x, ORGANIZATION, ORGANIZATION_TYPE, PLAYER_PROFILE_FLAG, PLAYER_ID, TEAM_ID_y, TEAM_ABBREVIATION_y, AGE, GP, W, L, W_PCT, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, TOV, STL, BLK, BLKA, PF, PFD, PTS, PLUS_MINUS, NBA_FANTASY_PTS, DD2, TD3, GP_RANK, W_RANK, L_RANK, W_PCT_RANK, MIN_RANK, FGM_RANK, FGA_RANK, FG_PCT_RANK, FG3M_RANK, FG3A_RANK, FG3_PCT_RANK, FTM_RANK, FTA_RANK, FT_PCT_RANK, OREB_RANK, DREB_RANK, REB_RANK, AST_RANK, TOV_RANK, STL_RANK, BLK_RANK, BLKA_RANK, PF_RANK, PFD_RANK, PTS_RANK, PLUS_MINUS_RANK, NBA_FANTASY_PTS_RANK, DD2_RANK, TD3_RANK, CFID, CFPARAMS, SEASON]
Index: []

[0 rows x 79 columns]